# OS11 - Exercises 7-8

In [1]:
from sympy import *

In [2]:
import numpy as np

In [3]:
import scipy.linalg as linalg

In [4]:
from scipy.optimize import linprog

### Previous functions useful here

In [5]:
def nodes_indexer(named_nodes):
    nodes = {}
    for i in range(len(named_nodes)):
        nodes[named_nodes[i]] = i
    return nodes

In [6]:
def ANMatrix_from_arcs(graph, num_nodes):
    num_arcs = len(graph)
    arcs = []
    MN = np.zeros((num_nodes, num_arcs)).astype(int)
    for a in range(len(graph)):
        MN[graph[a][0][0], a] = 1
        MN[graph[a][0][1], a] = -1
        arcs.append(graph[a][0])
    return MN

## Ex. 7 - Evacuation plan 

In [7]:
named_nodes = ['s', 'a', 'b', 't']   #node enumeration. Can be any non repeated inmutable.

In [8]:
nodes = nodes_indexer(named_nodes)

In [9]:
timed_graph = []

timed_graph.append((('s', 'a'), (5,1)))   #capacidad, tiempo
timed_graph.append((('s', 'b'), (10,3)))
timed_graph.append((('a', 't'), (3,1)))
timed_graph.append((('a', 'b'), (6,2)))
timed_graph.append((('b', 't'), (3,1)))

timed_graph


[(('s', 'a'), (5, 1)),
 (('s', 'b'), (10, 3)),
 (('a', 't'), (3, 1)),
 (('a', 'b'), (6, 2)),
 (('b', 't'), (3, 1))]

### Time Expansion

I will create new time-derived nodes

In [10]:
t_horizon = 6

In [11]:
t_named_nodes = [str(n) + '_' + str(i) for n in named_nodes for i in range(t_horizon)]
t_named_nodes.append('s')
t_named_nodes.append('t')

In [12]:
t_nodes = nodes_indexer(t_named_nodes)

Now, for each arc, I will "translate on time":

In [13]:
graph = []

for arc in timed_graph:
    for t in range(t_horizon):
        t_dest = t + arc[1][1]
        if t_dest < t_horizon:
            n_origen = arc[0][0] + '_' + str(t)
            n_dest = arc[0][1] + '_' + str(t_dest)
            n_cost = arc[1][0]
            graph.append(((n_origen, n_dest), n_cost))

In [14]:
graph

[(('s_0', 'a_1'), 5),
 (('s_1', 'a_2'), 5),
 (('s_2', 'a_3'), 5),
 (('s_3', 'a_4'), 5),
 (('s_4', 'a_5'), 5),
 (('s_0', 'b_3'), 10),
 (('s_1', 'b_4'), 10),
 (('s_2', 'b_5'), 10),
 (('a_0', 't_1'), 3),
 (('a_1', 't_2'), 3),
 (('a_2', 't_3'), 3),
 (('a_3', 't_4'), 3),
 (('a_4', 't_5'), 3),
 (('a_0', 'b_2'), 6),
 (('a_1', 'b_3'), 6),
 (('a_2', 'b_4'), 6),
 (('a_3', 'b_5'), 6),
 (('b_0', 't_1'), 3),
 (('b_1', 't_2'), 3),
 (('b_2', 't_3'), 3),
 (('b_3', 't_4'), 3),
 (('b_4', 't_5'), 3)]

Graph is actually incomplete. We must add node s and t, and related arcs.

In [15]:
for t in range(t_horizon):
    graph.append((('s', 's_' + str(t)), None))
    graph.append((('t_' + str(t), 't'), None))

graph.append((('t', 's'), None))

graph

[(('s_0', 'a_1'), 5),
 (('s_1', 'a_2'), 5),
 (('s_2', 'a_3'), 5),
 (('s_3', 'a_4'), 5),
 (('s_4', 'a_5'), 5),
 (('s_0', 'b_3'), 10),
 (('s_1', 'b_4'), 10),
 (('s_2', 'b_5'), 10),
 (('a_0', 't_1'), 3),
 (('a_1', 't_2'), 3),
 (('a_2', 't_3'), 3),
 (('a_3', 't_4'), 3),
 (('a_4', 't_5'), 3),
 (('a_0', 'b_2'), 6),
 (('a_1', 'b_3'), 6),
 (('a_2', 'b_4'), 6),
 (('a_3', 'b_5'), 6),
 (('b_0', 't_1'), 3),
 (('b_1', 't_2'), 3),
 (('b_2', 't_3'), 3),
 (('b_3', 't_4'), 3),
 (('b_4', 't_5'), 3),
 (('s', 's_0'), None),
 (('t_0', 't'), None),
 (('s', 's_1'), None),
 (('t_1', 't'), None),
 (('s', 's_2'), None),
 (('t_2', 't'), None),
 (('s', 's_3'), None),
 (('t_3', 't'), None),
 (('s', 's_4'), None),
 (('t_4', 't'), None),
 (('s', 's_5'), None),
 (('t_5', 't'), None),
 (('t', 's'), None)]

Graph data is in named form, I need in indexed form:

In [16]:
indexed_graph = [((t_nodes[a[0][0]], t_nodes[a[0][1]]), a[1]) for a in graph]
indexed_graph

[((0, 7), 5),
 ((1, 8), 5),
 ((2, 9), 5),
 ((3, 10), 5),
 ((4, 11), 5),
 ((0, 15), 10),
 ((1, 16), 10),
 ((2, 17), 10),
 ((6, 19), 3),
 ((7, 20), 3),
 ((8, 21), 3),
 ((9, 22), 3),
 ((10, 23), 3),
 ((6, 14), 6),
 ((7, 15), 6),
 ((8, 16), 6),
 ((9, 17), 6),
 ((12, 19), 3),
 ((13, 20), 3),
 ((14, 21), 3),
 ((15, 22), 3),
 ((16, 23), 3),
 ((24, 0), None),
 ((18, 25), None),
 ((24, 1), None),
 ((19, 25), None),
 ((24, 2), None),
 ((20, 25), None),
 ((24, 3), None),
 ((21, 25), None),
 ((24, 4), None),
 ((22, 25), None),
 ((24, 5), None),
 ((23, 25), None),
 ((25, 24), None)]

Now, I can create the arcs-nodes matrix

In [17]:
A = ANMatrix_from_arcs(indexed_graph, len(t_nodes))
A

array([[ 1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        -1,  0,  0],
       [ 0

Cost function:

In [18]:
c = np.zeros((len(graph)))
c[-1]=-1
c

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.])

Node balance vector b:
    

In [19]:
b = np.zeros((len(t_nodes)))
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

Arc bounds:

In [20]:
limites = [(0, a[1]) for a in graph]
limites

[(0, 5),
 (0, 5),
 (0, 5),
 (0, 5),
 (0, 5),
 (0, 10),
 (0, 10),
 (0, 10),
 (0, 3),
 (0, 3),
 (0, 3),
 (0, 3),
 (0, 3),
 (0, 6),
 (0, 6),
 (0, 6),
 (0, 6),
 (0, 3),
 (0, 3),
 (0, 3),
 (0, 3),
 (0, 3),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, None)]

### Resolution

In [21]:
r = linprog(c=c, A_eq = A, b_eq = b, bounds = limites, method='revised simplex')

<ipython-input-21-62916b0d23f2>:1: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  r = linprog(c=c, A_eq = A, b_eq = b, bounds = limites, method='revised simplex')


In [22]:
r

     con: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])
     fun: -18.0
 message: 'Optimization terminated successfully.'
     nit: 19
   slack: array([], dtype=float64)
  status: 0
 success: True
       x: array([ 3.,  3.,  3.,  3., -0.,  3.,  3.,  0.,  0.,  3.,  3.,  3.,  3.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  3.,  6.,  0.,  6.,  0.,
        3.,  3.,  3.,  3.,  0.,  6., -0.,  6., 18.])

### Results

Flow across the graph on t=6:

In [23]:
r.x[-1]

18.0

## Ex. 8 - Transshipment Problem

In [24]:
named_nodes = ['P1', 'P2', 'P3', 'S1', 'S2', 'D1', 'D2', 'D3']   #node enumeration. Can be any non repeated inmutable.

In [25]:
gen_graph = []

gen_graph.append((('P1', 'S1'), (100,200)))   #costo A, costo B
gen_graph.append((('P1', 'S2'), (100,200)))
gen_graph.append((('P2', 'S1'), (150,150)))
gen_graph.append((('P2', 'S2'), (150,150)))
gen_graph.append((('P3', 'S1'), (200,100)))
gen_graph.append((('P3', 'S2'), (200,100)))

gen_graph.append((('S1', 'D1'), (100,200)))
gen_graph.append((('S2', 'D1'), (100,200)))
gen_graph.append((('S1', 'D2'), (150,150)))
gen_graph.append((('S2', 'D2'), (150,150)))
gen_graph.append((('S1', 'D3'), (200,100)))
gen_graph.append((('S2', 'D3'), (200,100)))

gen_graph

[(('P1', 'S1'), (100, 200)),
 (('P1', 'S2'), (100, 200)),
 (('P2', 'S1'), (150, 150)),
 (('P2', 'S2'), (150, 150)),
 (('P3', 'S1'), (200, 100)),
 (('P3', 'S2'), (200, 100)),
 (('S1', 'D1'), (100, 200)),
 (('S2', 'D1'), (100, 200)),
 (('S1', 'D2'), (150, 150)),
 (('S2', 'D2'), (150, 150)),
 (('S1', 'D3'), (200, 100)),
 (('S2', 'D3'), (200, 100))]

Production:

In [26]:
Prod = {'P1': (20, 30), 'P2': (10, 40), 'P3': (30, 10)}

Demands:

In [27]:
Dem = {'D1': (-30, -40), 'D2': (-10, -20), 'D3': (-20, -20)}

Intermediate balances:

In [45]:
Depositos = {'S1': (0,0), 'S2':(0,0) }

### Product Expansion

I will duplicate nodes and graph for each product

In [29]:
products = ['A', 'B']

In [30]:
p_named_nodes = [str(n) + '_' + str(i) for n in named_nodes for i in products]
p_named_nodes

['P1_A',
 'P1_B',
 'P2_A',
 'P2_B',
 'P3_A',
 'P3_B',
 'S1_A',
 'S1_B',
 'S2_A',
 'S2_B',
 'D1_A',
 'D1_B',
 'D2_A',
 'D2_B',
 'D3_A',
 'D3_B']

In [31]:
p_nodes = nodes_indexer(p_named_nodes)

Now, for each arc, I will duplicate on product:

In [32]:
graph = []

for arc in gen_graph:
    for i in range(len(products)):
        p = products[i]
        n_origen = arc[0][0] + '_' + str(p)
        n_dest = arc[0][1] + '_' + str(p)
        n_cost = arc[1][i]
        graph.append(((n_origen, n_dest), n_cost))

In [33]:
graph

[(('P1_A', 'S1_A'), 100),
 (('P1_B', 'S1_B'), 200),
 (('P1_A', 'S2_A'), 100),
 (('P1_B', 'S2_B'), 200),
 (('P2_A', 'S1_A'), 150),
 (('P2_B', 'S1_B'), 150),
 (('P2_A', 'S2_A'), 150),
 (('P2_B', 'S2_B'), 150),
 (('P3_A', 'S1_A'), 200),
 (('P3_B', 'S1_B'), 100),
 (('P3_A', 'S2_A'), 200),
 (('P3_B', 'S2_B'), 100),
 (('S1_A', 'D1_A'), 100),
 (('S1_B', 'D1_B'), 200),
 (('S2_A', 'D1_A'), 100),
 (('S2_B', 'D1_B'), 200),
 (('S1_A', 'D2_A'), 150),
 (('S1_B', 'D2_B'), 150),
 (('S2_A', 'D2_A'), 150),
 (('S2_B', 'D2_B'), 150),
 (('S1_A', 'D3_A'), 200),
 (('S1_B', 'D3_B'), 100),
 (('S2_A', 'D3_A'), 200),
 (('S2_B', 'D3_B'), 100)]

Graph data is in named form, I need in indexed form:

In [34]:
indexed_graph = [((p_nodes[a[0][0]], p_nodes[a[0][1]]), a[1]) for a in graph]
indexed_graph

[((0, 6), 100),
 ((1, 7), 200),
 ((0, 8), 100),
 ((1, 9), 200),
 ((2, 6), 150),
 ((3, 7), 150),
 ((2, 8), 150),
 ((3, 9), 150),
 ((4, 6), 200),
 ((5, 7), 100),
 ((4, 8), 200),
 ((5, 9), 100),
 ((6, 10), 100),
 ((7, 11), 200),
 ((8, 10), 100),
 ((9, 11), 200),
 ((6, 12), 150),
 ((7, 13), 150),
 ((8, 12), 150),
 ((9, 13), 150),
 ((6, 14), 200),
 ((7, 15), 100),
 ((8, 14), 200),
 ((9, 15), 100)]

Now, I can create the arcs-nodes matrix

In [35]:
A = ANMatrix_from_arcs(indexed_graph, len(p_nodes))
A

array([[ 1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [-1,  0,  0,  0, -1,  0,  0,  0, -1,  0,  0,  0,  1,  0,  0,  0,
         1,  0,  0,  0,  1,  0,  0,  0],
       [ 0, -1,  0,  0,  0, -1,  0,  0,  0, -1,  0,  0,  0,  1,  0,  0,
         0,  1,  0,  0,  0,  1,  0,  0],
       [ 0,  0, -1,  0,  0,  0, -1,  0,  0,  0, -1,  0,  0,  0,  1,  0,
         0,  0,  1,  0, 

I split Node-Arc matrix on equal and less or equal parts.

Nodes up to P3_B represents plants, subject to equal or less restrictions:

In [36]:
A_leq = A[0:p_nodes['P3_B']+1]

A_leq

array([[1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0]])

In [37]:
A_eq = A[p_nodes['S1_A']:]
A_eq

array([[-1,  0,  0,  0, -1,  0,  0,  0, -1,  0,  0,  0,  1,  0,  0,  0,
         1,  0,  0,  0,  1,  0,  0,  0],
       [ 0, -1,  0,  0,  0, -1,  0,  0,  0, -1,  0,  0,  0,  1,  0,  0,
         0,  1,  0,  0,  0,  1,  0,  0],
       [ 0,  0, -1,  0,  0,  0, -1,  0,  0,  0, -1,  0,  0,  0,  1,  0,
         0,  0,  1,  0,  0,  0,  1,  0],
       [ 0,  0,  0, -1,  0,  0,  0, -1,  0,  0,  0, -1,  0,  0,  0,  1,
         0,  0,  0,  1,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0, -1,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0, -1,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        -1,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0, -1,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0, 

Cost function:

In [38]:
c = [a[1] for a in graph]
c = np.array(c)
c

array([100, 200, 100, 200, 150, 150, 150, 150, 200, 100, 200, 100, 100,
       200, 100, 200, 150, 150, 150, 150, 200, 100, 200, 100])

Demand vector b:

In [39]:
b_leq = []

for p in ['P1', 'P2', 'P3']:
    for q in Prod[p]:
        b_leq.append(q)
        
b_leq = np.array(b_leq)

b_leq

array([20, 30, 10, 40, 30, 10])

In [40]:
b_eq = []

for p in ['S1', 'S2']:
    for q in Depositos[p]:
        b_eq.append(q)

for p in ['D1', 'D2', 'D3']:
    for q in Dem[p]:
        b_eq.append(q)

b_eq = np.array(b_eq)

b_eq

array([  0,   0,   0,   0, -30, -40, -10, -20, -20, -20])

Bound vector:

In [41]:
limites = [(0, None) for a in graph]

### Resolution

In [42]:
r = linprog(c=c, A_eq = A_eq, b_eq = b_eq, A_ub = A_leq, b_ub=b_leq, bounds = limites, method='revised simplex')

In [43]:
r

     con: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
     fun: 44000.0
 message: 'Optimization terminated successfully.'
     nit: 15
   slack: array([0., 0., 0., 0., 0., 0.])
  status: 0
 success: True
       x: array([20., 30.,  0.,  0., 10., 40.,  0.,  0., 30., 10.,  0.,  0., 30.,
       40.,  0.,  0., 10., 20.,  0.,  0., 20., 20.,  0.,  0.])

### Results

In [44]:
for i in range(len(graph)):
    a=graph[i]
    print("Origin: {0}  Dest: {1} Product: {2} Qty.: {3}".format(a[0][0][0:2], a[0][1][0:2], a[0][0][3:], int(r.x[i])))

Origin: P1  Dest: S1 Product: A Qty.: 20
Origin: P1  Dest: S1 Product: B Qty.: 30
Origin: P1  Dest: S2 Product: A Qty.: 0
Origin: P1  Dest: S2 Product: B Qty.: 0
Origin: P2  Dest: S1 Product: A Qty.: 10
Origin: P2  Dest: S1 Product: B Qty.: 40
Origin: P2  Dest: S2 Product: A Qty.: 0
Origin: P2  Dest: S2 Product: B Qty.: 0
Origin: P3  Dest: S1 Product: A Qty.: 30
Origin: P3  Dest: S1 Product: B Qty.: 10
Origin: P3  Dest: S2 Product: A Qty.: 0
Origin: P3  Dest: S2 Product: B Qty.: 0
Origin: S1  Dest: D1 Product: A Qty.: 30
Origin: S1  Dest: D1 Product: B Qty.: 40
Origin: S2  Dest: D1 Product: A Qty.: 0
Origin: S2  Dest: D1 Product: B Qty.: 0
Origin: S1  Dest: D2 Product: A Qty.: 10
Origin: S1  Dest: D2 Product: B Qty.: 20
Origin: S2  Dest: D2 Product: A Qty.: 0
Origin: S2  Dest: D2 Product: B Qty.: 0
Origin: S1  Dest: D3 Product: A Qty.: 20
Origin: S1  Dest: D3 Product: B Qty.: 20
Origin: S2  Dest: D3 Product: A Qty.: 0
Origin: S2  Dest: D3 Product: B Qty.: 0


### Discussion

This problem is independent in products A and B. There are no restrictions involving both products and cost function is lineal on D.V. For this reason, we can conclude that solving for separate problems, one for each product, will give us the same results.